project_id = "yusmeyyxysulaogxjsiz"

[functions.sensors-ingest]
verify_jwt = false

[functions.sensors-latest]
verify_jwt = false

[functions.sensors-history]
verify_jwt = false

[functions.predict-water]
verify_jwt = false

[functions.predict-disease]
verify_jwt = false

[functions.zones]
verify_jwt = false

[functions.alerts]
verify_jwt = false

[functions.stats]
verify_jwt = false

[functions.water-trigger]
verify_jwt = false
